# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder "./..", "/vagrant"

  config.vm.provider :virtualbox do |v|
     v.customize ["modifyvm", :id, "--memory", 1048]
     v.name = "tetrifact"
  end

  config.vm.provision :shell, path: "provision.sh"
  config.vm.network "forwarded_port", guest: 3000, host: 3001
  config.vm.network "forwarded_port", guest: 49022, host: 49023
  config.vm.network "forwarded_port", guest: 3001, host: 3002

end
