# Example compose file for setting up a Tetrifact container.

version: "2"
services:
  tetrifact:
    image: shukriadams/tetrifact:latest
    container_name: tetrifact
    restart: unless-stopped
    environment:
      # This argument is REQUIRED for Tetrifact to bind properly to the container host port.
      ASPNETCORE_URLS : http://*:5000
    volumes:
      - ./data:/var/tetrifact/data/:rw
    ports:
    - "49022:5000"
