# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu1804"
    config.vm.hostname = "tetrifact"
    config.vm.synced_folder "./../..", "/vagrant", type: "nfs"
    config.vm.network "forwarded_port", guest: 5000, host: 5000
    config.vm.provision :shell, path: "./../provision.sh"  
    config.vm.provider :libvirt do |v|
        v.default_prefix = "tetrifact"
    end
end 