# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu2004"
    config.vm.hostname = "tetrifact"
    config.vm.synced_folder "./../..", "/vagrant", 
        type: "nfs",
        # !NOTE! you must set the NFS_VERSION env var variable on your host
        # machine, it should be something like "3" on ubuntu 22 and "4" on 24 or 
        # higher
        nfs_version: ENV['NFS_VERSION'],
        nfs_udp: false
    config.vm.network "forwarded_port", guest: 5000, host: 5000
    config.vm.provision :shell, path: "./../provision.sh"  
    config.vm.provider :libvirt do |v|
        v.default_prefix = "tetrifact"
        v.driver="qemu"
    end
end 