# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu1804"
    config.vm.hostname = "tetrifact"
    config.vm.synced_folder "./../..", "/vagrant", type: "nfs"
    config.vm.network "forwarded_port", guest: 3000, host: 3001
    config.vm.network "forwarded_port", guest: 49022, host: 49023
    config.vm.network "forwarded_port", guest: 3001, host: 3002
    config.vm.provision :shell, path: "./../provision.sh"  
    config.vm.provider :libvirt do |v|
        v.default_prefix = "tetrifact"
    end
end 